[username]
disabled = true

[hostname]
disabled = true

[container]
disabled = true

[conda]
format = "\\([$environment]($style)\\) "
ignore_base = false

[git_status]
ahead = "ğŸ”ºÃ—$count "
behind = "ï¿½Ã—$count "
conflicted = "âš”ï¸ "
deleted = "ï¿½Ã—$count "
diverged = "ğŸ”€ ğŸ”ºÃ—${ahead_count} ğŸ”»Ã—${behind_count} "
format = "$all_status$ahead_behind"
modified = "ğŸ“Ã—$count "
renamed = ""
staged = "ğŸ”’Ã—$count "
stashed = "ï¿½ "
style = "bright-white"
untracked = "ğŸ”“Ã—$count "
